b = require("./binance.js")
await b.lib.price("ATOMBUSD")
await b.lib.price("USTCBUSD")
c = require("./cosm.js")
await c.getprice("ustc")
await b.lib.price("USTCBUSD")
cw = c.walletfromkey(cosmk3)
cw = await c.walletfromkey(cosmk3)
ow = await c.walletfromkey(cosmk3,"osmo")
cwc = await c.connectrpc(cw)
owc = await c.connectrpc(ow)
await c.balance(owc)
f = await c.sendibctokens(cwc, ow.address, c.coins(9300000,"uatom"), channels.atom.c2o)
await c.balance(owc)
s = await c.swaposmosis(owc,c.getroute(['atom','osmo']),c.coins(10189000,ibctokens.atom), "100000000")
await c.balance(owc)
f = await c.sendibctokens(cwc, ow.address, c.coins(8000,"uatom"), channels.atom.c2o)
await c.balance(owc)
await b.lib.price("USTCBUSD")
await c.getprice("ustc")
await b.lib.balance("ustc")
await b.lib.balance("busd")
o = await b.api.newOrder("USTCBUSD", "BUY", "MARKET", { quantity: "1000" })
await b.lib.balance("busd")
await b.lib.balance("ustc")
o = await b.api.newOrder("USTCBUSD", "BUY", "MARKET", { quoteOrderQty: "15" })
o = await b.api.newOrder("USTCBUSD", "SELL", "MARKET", { quantity: "1000" })
await b.lib.balance("ustc")
await b.lib.balance("busd")
o.data
s = await c.swaposmosis(owc,c.getroute(['osmo','ustc']),c.coins(20,"uosmo"), "500")
await c.balance(owc)
